package apply

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"myarch/internal/render"
)

func shared(path, content string) render.File {
	return render.File{Plugin: "p", Path: path, Content: []byte(content), Merge: "ini"}
}

func TestIniMerge(t *testing.T) {
	app := "[Appearance]\nstyle=Breeze\nicon_theme=x\n\n[SettingsWindow]\ngeometry=@ByteArray(abc)\n"
	got := iniMerge(app, iniKeys("top=1\n[Appearance]\nstyle=Fusion\ncustom_palette=true\n[Fonts]\ngeneral=\"Mono,11\"\n"))
	want := "top=1\n[Appearance]\nstyle=Fusion\nicon_theme=x\ncustom_palette=true\n\n[SettingsWindow]\ngeometry=@ByteArray(abc)\n\n[Fonts]\ngeneral=\"Mono,11\"\n"
	if got != want {
		t.Fatalf("got:\n%s\nwant:\n%s", got, want)
	}
}

// The app rewrites its file (drops our comment, adds its window geometry):
// that's not an edit, and applying keeps what the app added.
func TestSharedFileTheAppRewrites(t *testing.T) {
	p := filepath.Join(t.TempDir(), "qt6ct.conf")
	rendered := "# Generated by myarch\n[Appearance]\nstyle=Fusion\n"
	owned := Owned{}
	ch, orphans, _ := Plan([]render.File{shared(p, rendered)}, owned)
	if ch[0].State != New {
		t.Fatalf("state %v", ch[0].State)
	}
	if _, err := Execute(ch, orphans, owned, false); err != nil {
		t.Fatal(err)
	}
	if b, _ := os.ReadFile(p); string(b) != rendered {
		t.Fatalf("a new shared file is written as rendered: %q", b)
	}
	os.WriteFile(p, []byte("[Appearance]\nstyle=Fusion\n\n[SettingsWindow]\ngeometry=x\n"), 0o644)

	ch, _, _ = Plan([]render.File{shared(p, rendered)}, owned)
	if ch[0].State != Unchanged {
		t.Fatalf("the app rewriting its file is not a change: %v", ch[0].State)
	}
	// A new theme: our key changes, the app's stays.
	ch, orphans, _ = Plan([]render.File{shared(p, "[Appearance]\nstyle=Windows\n")}, owned)
	if ch[0].State != Changed {
		t.Fatalf("state %v", ch[0].State)
	}
	Execute(ch, orphans, owned, false)
	if b, _ := os.ReadFile(p); !strings.Contains(string(b), "style=Windows") || !strings.Contains(string(b), "geometry=x") {
		t.Fatalf("got %s", b)
	}
}

func TestSharedFileEditedKeyIsAConflict(t *testing.T) {
	p := filepath.Join(t.TempDir(), "kdeglobals")
	owned := Owned{}
	ch, orphans, _ := Plan([]render.File{shared(p, "[KDE]\nwidgetStyle=Fusion\n")}, owned)
	Execute(ch, orphans, owned, false)
	// Someone picked another style in the app: one of myarch's keys.
	os.WriteFile(p, []byte("[KDE]\nwidgetStyle=Breeze\n"), 0o644)
	ch, orphans, _ = Plan([]render.File{shared(p, "[KDE]\nwidgetStyle=Oxygen\n")}, owned)
	if ch[0].State != Conflict {
		t.Fatalf("state %v", ch[0].State)
	}
	var ce *ConflictError
	if _, err := Execute(ch, orphans, owned, false); !errors.As(err, &ce) {
		t.Fatalf("want a conflict, got %v", err)
	}
	res, err := Execute(ch, orphans, owned, true)
	if err != nil {
		t.Fatal(err)
	}
	if b, _ := os.ReadFile(res.Backups[p]); string(b) != "[KDE]\nwidgetStyle=Breeze\n" {
		t.Errorf("backup %q", b)
	}
	if b, _ := os.ReadFile(p); !strings.Contains(string(b), "widgetStyle=Oxygen") {
		t.Errorf("after --adopt: %q", b)
	}
}

// A person's own kdeglobals, never written by myarch: its own value for one
// of myarch's keys is theirs (a conflict); keys it lacks are just added.
func TestSharedFileFirstTime(t *testing.T) {
	dir := t.TempDir()
	mine := filepath.Join(dir, "kdeglobals")
	os.WriteFile(mine, []byte("[KDE]\nwidgetStyle=Breeze\n[KFileDialog Settings]\nx=1\n"), 0o644)
	ch, _, _ := Plan([]render.File{shared(mine, "[KDE]\nwidgetStyle=Fusion\n")}, Owned{})
	if ch[0].State != Conflict {
		t.Fatalf("their own widgetStyle: %v", ch[0].State)
	}
	sparse := filepath.Join(dir, "qt6ct.conf")
	os.WriteFile(sparse, []byte("[SettingsWindow]\ngeometry=x\n"), 0o644)
	ch, _, _ = Plan([]render.File{shared(sparse, "[Appearance]\nstyle=Fusion\n")}, Owned{})
	if ch[0].State != Changed {
		t.Fatalf("only missing keys: %v", ch[0].State)
	}
}

// A shared file kept in a dotfiles repo, linked from ~/.config: written
// through the link, which stays a link.
func TestSharedFileThroughSymlink(t *testing.T) {
	dir := t.TempDir()
	real, link := filepath.Join(dir, "dotfiles-kdeglobals"), filepath.Join(dir, "kdeglobals")
	os.WriteFile(real, []byte("[General]\nx=1\n"), 0o644)
	os.Symlink(real, link)
	owned := Owned{}
	ch, orphans, _ := Plan([]render.File{shared(link, "[KDE]\nwidgetStyle=Fusion\n")}, owned)
	if _, err := Execute(ch, orphans, owned, false); err != nil {
		t.Fatal(err)
	}
	if fi, _ := os.Lstat(link); fi.Mode()&os.ModeSymlink == 0 {
		t.Fatal("the link was replaced by a file")
	}
	if b, _ := os.ReadFile(real); !strings.Contains(string(b), "widgetStyle=Fusion") || !strings.Contains(string(b), "x=1") {
		t.Fatalf("got %q", b)
	}
}

// A file owned whole by an older version, then rewritten by the app, is
// merged into, not a conflict; and a shared orphan stays.
func TestSharedFileFromWholeAndOrphan(t *testing.T) {
	p := filepath.Join(t.TempDir(), "qt6ct.conf")
	os.WriteFile(p, []byte("[Appearance]\nstyle=Fusion\n[SettingsWindow]\ngeometry=x\n"), 0o644)
	owned := Owned{p: Sum([]byte("# old\n[Appearance]\nstyle=Fusion\n"))}
	ch, orphans, _ := Plan([]render.File{shared(p, "[Appearance]\nstyle=Fusion\nicon_theme=A\n")}, owned)
	if ch[0].State != Changed {
		t.Fatalf("state %v", ch[0].State)
	}
	Execute(ch, orphans, owned, false)
	ch, orphans, _ = Plan(nil, owned)
	res, _ := Execute(ch, orphans, owned, false)
	if _, err := os.Stat(p); err != nil || len(res.Shared) != 1 {
		t.Fatalf("a shared file stays when its plugin goes: %v %+v", err, res)
	}
}
