using MyArch.Config;
using MyArch.Install;
using MyArch.Locale;
using MyArch.Plugins;
using MyArch.Rendering;
using MyArch.Themes;
using MyArch.Util;

namespace MyArch.Cli;

/// <summary>
/// The tools for writing plugins: new (a plugin to start from, of a kind),
/// check (everything a plugin's author should know before sharing it), dev
/// (applied again on every save), fork (a built-in plugin to change) and diff
/// (what the fork changed).
/// </summary>
public static partial class Program
{
    /// <summary>When set, apply keeps no snapshot: plugins dev applies on every save, and undo's history is for the person's own changes.</summary>
    static bool noSnapshots;

    static readonly string[] Kinds = ["bar", "panel", "window", "theme", "tools"];

    // --- new ---------------------------------------------------------------------

    /// <summary>new: a working plugin of a kind, to change into what one wants; in the plugin folder (on at once), or in DIR.</summary>
    internal static void PluginsNew(string id, string kind, string dir)
    {
        if (!Plugin.IdPattern().IsMatch(id)) throw new MyArchException($"plugin id \"{id}\": lowercase letters, digits and dashes");
        if (kind == "")
            kind = id.StartsWith("bar-") ? "bar" : id.StartsWith("theme-") ? "theme" : id.StartsWith("hypr-") ? "window" : "tools";
        if (!Kinds.Contains(kind)) throw new MyArchException($"--kind {kind}: one of {string.Join(", ", Kinds)}");
        var inPlace = dir == "";
        var to = inPlace ? Paths.Join(Git.Dir, id) : Path.GetFullPath(Paths.ExpandHome(dir));
        if (Paths.Exists(to) && (!Directory.Exists(to) || Directory.EnumerateFileSystemEntries(to).Any()))
            throw new MyArchException($"{Tilde(to)} is already there");
        if (inPlace && Plugin.Discover(PluginDirs()).Plugins.FirstOrDefault(p => p.Id == id) is { } there)
            throw new MyArchException($"there's a plugin {id} already ({Tilde(there.Dir)})" +
                (Paths.Dir(there.Dir) == Paths.Join(Root(), "plugins") ? $": to change it, myarch plugins fork {id}" : ""));
        var name = Humanize(id);
        foreach (var (rel, text) in Scaffold(kind, id))
        {
            var path = Paths.Join(to, rel);
            Files.CreateDirectory(Paths.Dir(path));
            File.WriteAllText(path, text.Replace("@ID@", id).Replace("@NAME@", name).Replace("@APP@", AppOf(id)), Files.Utf8);
        }
        Console.WriteLine($"created {Tilde(to)}: a {kind} plugin");
        foreach (var f in Directory.GetFiles(to, "*", SearchOption.AllDirectories).Order(StringComparer.Ordinal))
            Console.WriteLine("  " + Path.GetRelativePath(to, f));
        var at = inPlace ? id : Tilde(to);
        Console.WriteLine($"""

            next:
              myarch plugins dev {at}     apply it on every save, while you change it
              myarch plugins check {at}   before sharing it: every theme, every language
            """);
    }

    /// <summary>font-size-picker -> "Font size picker" (bar- and friends dropped).</summary>
    static string Humanize(string id)
    {
        foreach (var pre in new[] { "bar-", "theme-", "hypr-" })
            if (id.StartsWith(pre) && id.Length > pre.Length) id = id[pre.Length..];
        var s = id.Replace('-', ' ');
        return char.ToUpperInvariant(s[0]) + s[1..];
    }

    static string AppOf(string id) => id.StartsWith("theme-") && id.Length > 6 ? id[6..] : id;

    static List<(string, string)> Scaffold(string kind, string id)
    {
        var files = new List<(string, string)>();
        switch (kind)
        {
            case "bar":
                files.Add(("plugin.toml", """
                    [plugin]
                    id = "@ID@"
                    name = "@NAME@"
                    version = "0.1.0"
                    api = 1
                    description = "What it shows in the bar, in one line"
                    requires = ["shell-bar"]
                    categories = ["bar"]

                    [settings]
                    # How often to read it again, in seconds.
                    refresh_seconds = { default = 30, min = 1, max = 3600 }

                    # A widget: shell-bar loads every file in widgets/left, center
                    # and right, in the order of their names.
                    [[targets]]
                    template = "Widget.qml.tmpl"
                    output = "~/.config/quickshell/myarch/widgets/right/50-@ID@.qml"
                    reload = "sh ~/.local/share/myarch/bin/shell-reload"

                    """));
                files.Add(("Widget.qml.tmpl", """
                    // Generated by myarch (plugin {{ plugin }}).
                    import QtQuick
                    import Quickshell.Io
                    import qs
                    import "../../components/kit"

                    // BarItem lays its children out in a row, centered, and takes
                    // their width: no anchors on them.
                    BarItem {
                      id: root
                      property string value: "…"

                      Label {
                        // Text in the person's language: tq is a quoted string.
                        text: {{ tq "label" }}.arg(root.value)
                        color: Theme.fgMuted
                      }

                      Process {
                        id: read
                        command: ["cut", "-d", " ", "-f", "1", "/proc/loadavg"]
                        stdout: StdioCollector { onStreamFinished: root.value = this.text.trim() }
                      }

                      Timer {
                        interval: {{ settings.refresh_seconds }} * 1000
                        running: true
                        repeat: true
                        triggeredOnStart: true
                        onTriggered: read.running = true
                      }
                    }

                    """));
                files.Add(("locales/en.toml", """
                    label = "load %1"

                    """));
                files.Add(("locales/es.toml", """
                    "plugin.name" = "@NAME@"
                    "plugin.description" = "Lo que muestra en la barra, en una línea"
                    label = "carga %1"
                    "setting.refresh_seconds" = "Actualizar cada"
                    "setting.refresh_seconds.help" = "Cada cuántos segundos leerlo de nuevo."

                    """));
                break;
            case "panel":
                files.Add(("plugin.toml", """
                    [plugin]
                    id = "@ID@"
                    name = "@NAME@"
                    version = "0.1.0"
                    api = 1
                    description = "What the panel is for, in one line"
                    requires = ["shell-bar", "hypr-base"]
                    categories = ["panel"]

                    [settings]
                    # Opens the panel.
                    key = "SUPER + ALT + P"

                    # A panel: the shell opens panels/NAME.qml with
                    # qs ipc -c myarch call myarch panel NAME.
                    [[targets]]
                    template = "Panel.qml.tmpl"
                    output = "~/.config/quickshell/myarch/panels/@ID@.qml"
                    reload = "sh ~/.local/share/myarch/bin/shell-reload"

                    [[targets]]
                    template = "bind.lua.tmpl"
                    output = "~/.config/hypr/myarch/@ID@.lua"
                    reload = "hyprctl reload >/dev/null"

                    # In the command palette, with its key.
                    [[actions]]
                    name = "{{ t \"open\" }}"
                    run = "qs ipc -c myarch call myarch panel @ID@"
                    key = "{{ settings.key }}"
                    keywords = "{{ t \"open.kw\" }}"

                    """));
                files.Add(("Panel.qml.tmpl", """
                    // Generated by myarch (plugin {{ plugin }}).
                    import QtQuick
                    import QtQuick.Layouts
                    import Quickshell
                    import Quickshell.Wayland
                    import qs
                    import "../components/kit"

                    Item {
                      id: root
                      property bool open: false

                      function toggle() { open = !open }
                      function close() { open = false }

                      PanelWindow {
                        visible: root.open
                        implicitWidth: 480
                        implicitHeight: 320
                        color: "transparent"
                        exclusionMode: ExclusionMode.Ignore
                        WlrLayershell.layer: WlrLayer.Overlay
                        // "myarch-panel-…": SUPER + Q closes it (hypr-base).
                        WlrLayershell.namespace: "myarch-panel-{{ plugin }}"
                        WlrLayershell.keyboardFocus: WlrKeyboardFocus.Exclusive

                        Rectangle {
                          anchors.fill: parent
                          color: Theme.surfaceRaised
                          border.color: Theme.border
                          border.width: 1
                          radius: Theme.radius
                          focus: true
                          Keys.onEscapePressed: root.close()

                          ColumnLayout {
                            anchors.fill: parent
                            anchors.margins: 16
                            spacing: 10
                            Caption { text: {{ tq "title" }}.toUpperCase() }
                            Label {
                              text: {{ tq "hello" }}
                              wrapMode: Text.Wrap
                              Layout.fillWidth: true
                            }
                            Item { Layout.fillHeight: true }
                            Button {
                              text: {{ tq "close" }}
                              primary: true
                              onClicked: root.close()
                            }
                          }
                        }
                      }
                    }

                    """));
                files.Add(("bind.lua.tmpl", """
                    -- Generated by myarch (plugin {{ plugin }}): opens the panel.
                    hl.bind({{ lq settings.key }}, hl.dsp.exec_cmd("qs ipc -c myarch call myarch panel {{ plugin }}"))

                    """));
                files.Add(("locales/en.toml", """
                    title = "@NAME@"
                    hello = "Everything in the theme: colors, fonts and shape come from Theme."
                    close = "Close"
                    open = "Open @NAME@"
                    "open.kw" = "panel"

                    """));
                files.Add(("locales/es.toml", """
                    "plugin.name" = "@NAME@"
                    "plugin.description" = "Para qué es el panel, en una línea"
                    title = "@NAME@"
                    hello = "Todo con el tema: colores, fuentes y forma vienen de Theme."
                    close = "Cerrar"
                    open = "Abrir @NAME@"
                    "open.kw" = "panel"
                    "setting.key" = "Tecla"
                    "setting.key.help" = "Abre el panel."

                    """));
                break;
            case "window":
                files.Add(("plugin.toml", """
                    [plugin]
                    id = "@ID@"
                    name = "@NAME@"
                    version = "0.1.0"
                    api = 1
                    description = "What it changes in how windows behave, in one line"
                    requires = ["hypr-base"]
                    categories = ["window"]

                    [settings]
                    # The key that does it.
                    key = "SUPER + ALT + G"

                    # A fragment of Hyprland's Lua config: hypr-base loads every
                    # file in ~/.config/hypr/myarch/.
                    [[targets]]
                    template = "window.lua.tmpl"
                    output = "~/.config/hypr/myarch/@ID@.lua"
                    reload = "hyprctl reload >/dev/null"

                    [[actions]]
                    name = "{{ t \"toggle\" }}"
                    key = "{{ settings.key }}"
                    keywords = "{{ t \"toggle.kw\" }}"

                    """));
                files.Add(("window.lua.tmpl", """
                    -- Generated by myarch (plugin {{ plugin }}): {{ inline settings.key }} toggles the gaps.
                    local on = true
                    hl.bind({{ lq settings.key }}, function()
                      on = not on
                      hl.config({ general = { gaps_in = on and {{ theme.shape.gap_in }} or 0, gaps_out = on and {{ theme.shape.gap_out }} or 0 } })
                    end)

                    """));
                files.Add(("locales/en.toml", """
                    toggle = "Toggle the gaps between windows"
                    "toggle.kw" = "gaps margins"

                    """));
                files.Add(("locales/es.toml", """
                    "plugin.name" = "@NAME@"
                    "plugin.description" = "Lo que cambia en cómo se comportan las ventanas, en una línea"
                    toggle = "Alternar los huecos entre ventanas"
                    "toggle.kw" = "huecos márgenes"
                    "setting.key" = "Tecla"
                    "setting.key.help" = "La tecla que lo hace."

                    """));
                break;
            case "theme":
                files.Add(("plugin.toml", """
                    [plugin]
                    id = "@ID@"
                    name = "@NAME@ theme"
                    version = "0.1.0"
                    api = 1
                    description = "@APP@ in the theme"
                    categories = ["theme"]

                    # The file @APP@ reads its colors from, from the theme's: when
                    # the theme changes, so does it.
                    [[targets]]
                    template = "colors.tmpl"
                    output = "~/.config/@APP@/myarch-colors.ini"

                    """));
                files.Add(("colors.tmpl", """
                    # Generated by myarch (plugin {{ plugin }}): the {{ theme.meta.name }} theme's colors.
                    background = {{ c "bg" }}
                    foreground = {{ c "fg" }}
                    muted = {{ c "fg_muted" }}
                    accent = {{ c "accent" }}
                    selection = {{ c "selection" }}
                    error = {{ c "danger" }}
                    font = {{ inline theme.font.mono }}

                    """));
                files.Add(("locales/es.toml", """
                    "plugin.name" = "Tema de @APP@"
                    "plugin.description" = "@APP@ con el tema"

                    """));
                break;
            default:
                files.Add(("plugin.toml", """
                    [plugin]
                    id = "@ID@"
                    name = "@NAME@"
                    version = "0.1.0"
                    api = 1
                    description = "What it does, in one line"
                    categories = ["tools"]

                    [settings]
                    # The folder it opens, in your home.
                    folder = { default = "Documents", kind = "path" }

                    # In the command palette: a command, and a key if you want one.
                    [[actions]]
                    name = "{{ t \"open\" }}"
                    run = "xdg-open {{ shq (home + \"/\" + settings.folder) }}"
                    keywords = "{{ t \"open.kw\" }}"

                    """));
                files.Add(("locales/en.toml", """
                    open = "Open the folder"
                    "open.kw" = "files documents"

                    """));
                files.Add(("locales/es.toml", """
                    "plugin.name" = "@NAME@"
                    "plugin.description" = "Lo que hace, en una línea"
                    open = "Abrir la carpeta"
                    "open.kw" = "archivos documentos"
                    "setting.folder" = "Carpeta"
                    "setting.folder.help" = "La carpeta que abre, dentro de tu carpeta personal."

                    """));
                break;
        }
        files.Add(("README.md", """
            # @NAME@

            What it does, and how to use it: this is its page in the Plugins
            panel. A README.es.md (or another language's) is shown instead in
            that language.

            ## Settings

            Each one is described by the comment above it in plugin.toml.

            """));
        return files;
    }

    // --- check -------------------------------------------------------------------

    /// <summary>
    /// check: what a plugin's author should know before sharing it. It must
    /// load and render with every theme, in every language it has, with its
    /// settings' defaults; and it should say what it is, in the languages it
    /// has. Errors make it fail; warnings are advice.
    /// </summary>
    internal static int PluginsCheck(string arg)
    {
        var dir = PluginDirOf(arg);
        var errors = new List<string>();
        var warnings = new List<string>();
        Plugin p;
        try
        {
            p = Plugin.Load(dir);
        }
        catch (MyArchException e)
        {
            Console.WriteLine($"{Style.Red}✗{Style.Reset} {e.Message}");
            return 1;
        }
        if (Paths.Base(dir) != p.Id && !IsLink(dir))
            warnings.Add($"its folder is {Paths.Base(dir)}, its id {p.Id}: installed, the folder is named after the id");

        var caps = p.Capabilities();
        if (caps.Count > 0 && caps[0].StartsWith("(unreadable")) errors.Add(caps[0][1..^1]);

        // Its languages: en, and every locales/*.toml.
        var langs = new List<string> { Languages.Fallback };
        var locales = Paths.Join(dir, "locales");
        if (Directory.Exists(locales))
            langs.AddRange(Directory.GetFiles(locales, "*.toml").Select(f => Path.GetFileNameWithoutExtension(f))
                .Where(l => l != Languages.Fallback).Order(StringComparer.Ordinal));
        var en = Paths.Join(locales, Languages.Fallback + ".toml");
        foreach (var lang in langs.Skip(1))
        {
            try
            {
                MyArch.Locale.Catalog.Load(p.Id, dir, lang);
                var own = Toml.ReadFile(Paths.Join(locales, lang + ".toml")) ?? new();
                var missing = new List<string>();
                if (!own.ContainsKey("plugin.name")) missing.Add("plugin.name");
                if (!own.ContainsKey("plugin.description")) missing.Add("plugin.description");
                foreach (var k in p.Settings.Keys.Order(StringComparer.Ordinal))
                    if (!own.ContainsKey("setting." + k)) missing.Add("setting." + k);
                if (File.Exists(en))
                    foreach (var k in (Toml.ReadFile(en) ?? new()).Keys.Order(StringComparer.Ordinal))
                        if (!own.ContainsKey(k)) missing.Add(k);
                if (missing.Count > 0)
                    warnings.Add($"locales/{lang}.toml: in English still: {string.Join(", ", missing)}");
            }
            catch (MyArchException e)
            {
                errors.Add(e.Message);
            }
        }
        if (langs.Count == 1)
            warnings.Add("only in English: a locales/es.toml (plugin.name, plugin.description, setting.KEY…) puts it in Spanish");

        // What it needs, as installed here, and it in its place.
        var (all, broken) = Plugin.Discover(PluginDirs());
        var set = new Dictionary<string, Plugin> { [p.Id] = p };
        var queue = new Queue<Plugin>([p]);
        while (queue.Count > 0)
            foreach (var r in queue.Dequeue().Meta.Requires)
            {
                Requirement req;
                try
                {
                    req = Requirement.Parse(r);
                }
                catch (MyArchException e)
                {
                    errors.Add(e.Message);
                    continue;
                }
                if (set.ContainsKey(req.Id)) continue;
                if (all.FirstOrDefault(x => x.Id == req.Id) is { } dep)
                {
                    set[req.Id] = dep;
                    queue.Enqueue(dep);
                }
                else errors.Add($"needs {req.Id}, which isn't here" + (broken.TryGetValue(req.Id, out var why) ? $": {why}" : ""));
            }
        var problems = Dependencies.Unmet(set.Values, set.Values, broken).Where(x => x.Plugin == p.Id).Select(x => x.Text).ToList();
        errors.AddRange(problems);

        // Every theme, every language, with the defaults: what it renders to
        // must not depend on the theme or language its author uses.
        var themes = Theme.List(ThemeDirs());
        var renders = 0;
        // The same mistake in every theme is said once: where, and how many more.
        var failed = new List<(string Where, string Text, string Key)>();
        if (errors.Count == 0)
            foreach (var tid in themes)
            {
                var t = Theme.Load(ThemeDirs(), tid);
                foreach (var lang in langs)
                {
                    try
                    {
                        var output = Renderer.All([.. set.Values], t, _ => null, lang);
                        renders++;
                        foreach (var f in output.Files.Where(f => f.Plugin == p.Id && f.Content.Trim() == ""))
                            warnings.Add($"{Tilde(f.Path)} renders empty (theme {tid}, {lang})");
                    }
                    catch (MyArchException e)
                    {
                        failed.Add(($"theme {tid}, {lang}", e.Message, e.Message.Replace($"\"{tid}\"", "\"…\"")));
                    }
                }
            }

        foreach (var g in failed.GroupBy(f => f.Key))
            errors.Add($"{g.First().Where}{(g.Count() > 1 ? $" (and {g.Count() - 1} more)" : "")}: {g.First().Text}");

        if (p.Meta.Description == "") warnings.Add("no description: [plugin] description = \"…\", one line on what it does");
        if (p.Meta.Categories.Count == 0)
            warnings.Add($"no categories: taken for {string.Join(", ", p.CategoriesOrGuess())}; say it (categories = [\"{p.CategoriesOrGuess()[0]}\"])");
        if (!Directory.GetFiles(dir).Any(f => Paths.Base(f).Equals("README.md", StringComparison.OrdinalIgnoreCase)))
            warnings.Add("no README.md: its page in the Plugins panel is empty");
        foreach (var k in p.Settings.Keys.Order(StringComparer.Ordinal))
            if ((p.SettingsInfo.GetValueOrDefault(k)?.Description ?? "") == "")
                warnings.Add($"setting {k}: no description (a # comment above it in plugin.toml)");
        if (p.Targets.Any(t => t.System) && p.Hardware == null)
            errors.Add("writes system files, but has no [hardware] rules");

        foreach (var e in errors.Distinct()) Console.WriteLine($"{Style.Red}✗{Style.Reset} {e}");
        foreach (var w in warnings.Distinct()) Console.WriteLine($"{Style.Amber}!{Style.Reset} {w}");
        Console.WriteLine($"{p.Id} {p.Meta.Version}: {Plural(renders, "render", "renders")} ({themes.Count} themes × {string.Join(", ", langs)}), " +
            $"{Plural(caps.Count, "capability", "capabilities")}, {Plural(errors.Distinct().Count(), "error", "errors")}, {Plural(warnings.Distinct().Count(), "warning", "warnings")}");
        if (errors.Count == 0)
        {
            Console.WriteLine("\nIt would be able to:");
            foreach (var cap in caps) Console.WriteLine($"  - {cap}");
        }
        return errors.Count > 0 ? 1 : 0;
    }

    /// <summary>A plugin's folder: DIR (with a plugin.toml), or an installed plugin's id; "" is the current folder.</summary>
    static string PluginDirOf(string arg)
    {
        if (arg == "") arg = ".";
        var d = Paths.ExpandHome(arg);
        if (File.Exists(Paths.Join(d, "plugin.toml"))) return Path.GetFullPath(d);
        if (Plugin.IdPattern().IsMatch(arg) && Plugin.Discover(PluginDirs()).Plugins.FirstOrDefault(p => p.Id == arg) is { } p) return p.Dir;
        throw new MyArchException(arg == "." ? "no plugin.toml here: myarch plugins check ID|DIR" : $"no plugin \"{arg}\" (an id, or a folder with a plugin.toml)");
    }

    // --- dev ---------------------------------------------------------------------

    /// <summary>
    /// dev: the plugin applied again whenever one of its files changes, until
    /// Ctrl+C. A folder elsewhere (the plugin's own repository) is linked
    /// into the plugin folder first, and stays linked: myarch plugins remove
    /// ID takes the link away, not the folder.
    /// </summary>
    static void PluginsDev(string arg)
    {
        var dir = PluginDirOf(arg);
        var p = Plugin.Load(dir);
        var place = Paths.Join(Git.Dir, p.Id);
        if (Paths.Dir(dir) == Paths.Join(Root(), "plugins"))
            throw new MyArchException($"{p.Id} is built in: to change it, myarch plugins fork {p.Id}, then myarch plugins dev {p.Id}");
        if (PluginsLock.Load().Get(p.Id) != null)
            throw new MyArchException($"{p.Id} is installed from git: work on your clone of it (myarch plugins dev ~/src/{p.Id}), after myarch plugins remove {p.Id}");
        if (p.Hardware != null || p.Targets.Any(t => t.System))
            throw new MyArchException($"{p.Id} is a hardware plugin: check it with myarch plugins check, apply it with myarch apply --system");
        if (Path.GetFullPath(dir) != Path.GetFullPath(place))
        {
            if (new FileInfo(place).LinkTarget is { } target)
            {
                if (Path.GetFullPath(target, Git.Dir) != Path.GetFullPath(dir))
                    throw new MyArchException($"{Tilde(place)} is a link to {target} already: myarch plugins remove {p.Id} first");
            }
            else if (Paths.Exists(place))
                throw new MyArchException($"there's a plugin {p.Id} in {Tilde(place)} already");
            else
            {
                if (Plugin.Discover([Paths.Join(Root(), "plugins")]).Plugins.Any(b => b.Id == p.Id))
                    Console.WriteLine($"{Style.Amber}it takes the built-in {p.Id}'s place while linked{Style.Reset}");
                Files.CreateDirectory(Git.Dir);
                Directory.CreateSymbolicLink(place, dir);
                Console.WriteLine($"linked {Tilde(place)} -> {Tilde(dir)} (myarch plugins remove {p.Id} unlinks it)");
            }
        }
        var cfg = Settings.Load();
        if (!cfg.IsOn(p))
        {
            cfg.TurnOn(p);
            cfg.Save();
            Console.WriteLine($"turned {p.Id} on");
        }
        noSnapshots = true;
        Console.WriteLine($"{Style.Dim}applying {p.Id} on every save, without undo snapshots; Ctrl+C to stop{Style.Reset}");
        string? seen = null;
        while (true)
        {
            var now = Fingerprint(dir);
            if (now != seen)
            {
                // Saving writes a file or several: wait for them to settle.
                Thread.Sleep(150);
                now = Fingerprint(dir);
                seen = now;
                Console.WriteLine($"\n{Style.Bold}{DateTime.Now:HH:mm:ss}{Style.Reset} {p.Id}");
                var since = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
                try
                {
                    CmdApply(["--changes-only"]);
                    // What the shell says of its QML, once it has loaded it.
                    var qml = QmlOutputs(dir);
                    if (qml.Count > 0)
                    {
                        Thread.Sleep(1500);
                        foreach (var w in ShellWarnings(qml, since)) Console.WriteLine($"{Style.Red}✗{Style.Reset} {w}");
                    }
                }
                // Whatever this save got wrong (a file that isn't myarch's in the
                // way, too), the next save tries again.
                catch (Exception e) when (e is MyArchException or Applying.ConflictException or IOException or UnauthorizedAccessException)
                {
                    Console.WriteLine($"{Style.Red}✗{Style.Reset} {e.Message}");
                }
            }
            Thread.Sleep(300);
        }
    }

    /// <summary>The plugin's QML files, where they're written (read again: the manifest may have changed).</summary>
    static List<string> QmlOutputs(string dir)
    {
        try
        {
            return Plugin.Load(dir).Targets.Where(t => t.Each.Count == 0 && t.Output.EndsWith(".qml"))
                .Select(t => Paths.ExpandHome(t.Output)).ToList();
        }
        catch (MyArchException)
        {
            return [];
        }
    }

    [System.Text.RegularExpressions.GeneratedRegex(@"file://(?<file>[^?\s]+)\?generation=(?<gen>\d+)\[(?<line>-?\d+):(?<col>-?\d+)\]: (?<text>.*)")]
    private static partial System.Text.RegularExpressions.Regex ShellLogLine();

    /// <summary>
    /// The running shell's warnings about these files since a time (its
    /// reloads are numbered by the time, in ms): a QML mistake shows only
    /// when the shell loads the file.
    /// </summary>
    static List<string> ShellWarnings(List<string> files, long sinceMs)
    {
        string log;
        try
        {
            using var proc = System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo("sh",
                ["-c", "pid=$(pgrep -n -f '^qs -c myarch') && exec qs log --pid \"$pid\" -t 400"])
            {
                RedirectStandardOutput = true,
                RedirectStandardError = true,
            })!;
            log = proc.StandardOutput.ReadToEnd();
            proc.WaitForExit();
        }
        catch (Exception e) when (e is System.ComponentModel.Win32Exception or IOException)
        {
            return [];
        }
        var out_ = new List<string>();
        foreach (var raw in log.Split('\n'))
        {
            var m = ShellLogLine().Match(Ansi().Replace(raw, ""));
            if (!m.Success || !files.Contains(m.Groups["file"].Value) || long.Parse(m.Groups["gen"].Value) < sinceMs) continue;
            var w = $"{Tilde(m.Groups["file"].Value)}:{m.Groups["line"].Value}: {m.Groups["text"].Value.Trim()}";
            if (!out_.Contains(w)) out_.Add(w);
        }
        return out_;
    }

    /// <summary>What the plugin's files are now: names, sizes and times (not .git).</summary>
    static string Fingerprint(string dir)
    {
        var sb = new System.Text.StringBuilder();
        try
        {
            foreach (var f in Directory.EnumerateFiles(dir, "*", SearchOption.AllDirectories).Order(StringComparer.Ordinal))
            {
                if (f.Contains("/.git/")) continue;
                var fi = new FileInfo(f);
                sb.Append(f).Append('\0').Append(fi.Length).Append('\0').Append(fi.LastWriteTimeUtc.Ticks).Append('\n');
            }
        }
        catch (Exception e) when (e is IOException or UnauthorizedAccessException)
        {
            sb.Append(e.Message); // mid-save: tried again
        }
        return sb.ToString();
    }

    // --- fork and diff -----------------------------------------------------------

    /// <summary>
    /// fork: a built-in plugin copied into the plugin folder, to change: the
    /// copy takes its place. With NEW, a copy under another id, next to it
    /// (from git too): a plugin to start from.
    /// </summary>
    internal static void PluginsFork(string id, string newId)
    {
        var c = Catalog.Load();
        var p = c.Find(id) ?? throw new MyArchException(c.Broken.GetValueOrDefault(id) ?? $"no plugin \"{id}\"");
        var builtIn = c.Origin(p) == "built-in";
        if (newId == "")
        {
            if (!builtIn) throw new MyArchException($"{id} is {c.Origin(p)}: it's yours to change already, or give the copy a new id: myarch plugins fork {id} NEW");
            newId = id;
        }
        else if (!Plugin.IdPattern().IsMatch(newId)) throw new MyArchException($"plugin id \"{newId}\": lowercase letters, digits and dashes");
        else if (newId != id && c.Find(newId) != null) throw new MyArchException($"there's a plugin {newId} already");
        if (p.Hardware != null && newId == id)
            Console.WriteLine($"{Style.Amber}a hardware plugin: myarch apply --system writes what you change, as root{Style.Reset}");
        var to = Paths.Join(Git.Dir, newId);
        if (Paths.Exists(to)) throw new MyArchException($"{Tilde(to)} is already there");
        CopyTree(p.Dir, to);
        if (newId != id)
        {
            var manifest = Paths.Join(to, "plugin.toml");
            var text = File.ReadAllText(manifest);
            var renamed = System.Text.RegularExpressions.Regex.Replace(text, "(?m)^(id\\s*=\\s*)\"" + id + "\"", "$1\"" + newId + "\"");
            File.WriteAllText(manifest, renamed, Files.Utf8);
            Console.WriteLine($"copied {id} to {Tilde(to)} as {newId}");
            // Both would write the same files: the copy's are for it to change.
            if (c.Cfg.IsOn(p) && p.Targets.Count > 0 && Dependencies.Dependents(id, c.Enabled()).Count == 0)
            {
                c.Cfg.TurnOff(p);
                c.Cfg.Save();
                Console.WriteLine($"turned {id} off: both would write {string.Join(", ", p.Targets.Select(t => t.Output).Take(2))}…; change {newId}'s outputs to have both");
            }
            else if (p.Targets.Count > 0)
                Console.WriteLine($"{Style.Amber}change {newId}'s outputs: {id} writes the same files{Style.Reset}");
        }
        else
            Console.WriteLine($"""
                copied {id} to {Tilde(to)}: your copy takes the built-in's place
                  myarch plugins dev {id}    apply it on every save
                  myarch plugins diff {id}   what you've changed
                  delete {Tilde(to)} to go back to the built-in
                """);
    }

    /// <summary>A folder copied, files only: no links, no .git.</summary>
    static void CopyTree(string from, string to)
    {
        Files.CreateDirectory(to);
        foreach (var e in Directory.EnumerateFileSystemEntries(from))
        {
            var name = Paths.Base(e);
            if (name == ".git" || new FileInfo(e).LinkTarget != null) continue;
            if (Directory.Exists(e)) CopyTree(e, Paths.Join(to, name));
            else File.Copy(e, Paths.Join(to, name));
        }
    }

    /// <summary>diff: what a fork changed from the built-in plugin it takes the place of.</summary>
    internal static void PluginsDiff(string id)
    {
        if (!Plugin.IdPattern().IsMatch(id)) throw new MyArchException($"plugin id \"{id}\": lowercase letters, digits and dashes");
        var mine = Paths.Join(Git.Dir, id);
        var theirs = Paths.Join(Root(), "plugins", id);
        if (!Directory.Exists(mine) || !Directory.Exists(theirs))
            throw new MyArchException($"{id} isn't a fork of a built-in plugin (myarch plugins fork {id})");
        static IEnumerable<string> Rel(string root) => Directory.Exists(root)
            ? Directory.EnumerateFiles(root, "*", SearchOption.AllDirectories).Select(f => Path.GetRelativePath(root, f)).Where(f => !f.StartsWith(".git/"))
            : [];
        var any = false;
        foreach (var rel in Rel(theirs).Union(Rel(mine)).Order(StringComparer.Ordinal))
        {
            var a = Paths.Join(theirs, rel);
            var b = Paths.Join(mine, rel);
            var ta = File.Exists(a) ? File.ReadAllText(a) : "";
            var tb = File.Exists(b) ? File.ReadAllText(b) : "";
            if (ta == tb) continue;
            any = true;
            Console.Write(Diff.Unified(ta, tb, File.Exists(a) ? "built-in/" + rel : "/dev/null", File.Exists(b) ? "yours/" + rel : "/dev/null"));
        }
        if (!any) Console.WriteLine($"{id}: the same as the built-in");
    }
}
