using Mazapan.Applying;
using Mazapan.Rendering;
using static Mazapan.Tests.Applying.ApplyTests;

namespace Mazapan.Tests.Applying;

public sealed class SharedTests : IDisposable
{
    readonly TempDir dir = new();

    public void Dispose() => dir.Dispose();

    static RenderedFile Shared(string path, string content) =>
        new() { Plugin = "p", Path = path, Content = content, Merge = "ini" };

    static (List<Change> Changes, List<string> Orphans) Plan(Owned owned, params RenderedFile[] files) =>
        Apply.Plan(files, owned);

    [Fact]
    public void IniMerge()
    {
        var app = "[Appearance]\nstyle=Breeze\nicon_theme=x\n\n[SettingsWindow]\ngeometry=@ByteArray(abc)\n";
        var got = Apply.IniMerge(app, Apply.IniKeys("top=1\n[Appearance]\nstyle=Fusion\ncustom_palette=true\n[Fonts]\ngeneral=\"Mono,11\"\n"));
        var want = "top=1\n[Appearance]\nstyle=Fusion\nicon_theme=x\ncustom_palette=true\n\n[SettingsWindow]\ngeometry=@ByteArray(abc)\n\n[Fonts]\ngeneral=\"Mono,11\"\n";
        Assert.Equal(want, got);
    }

    // The app rewrites its file (drops our comment, adds its window geometry):
    // that's not an edit, and applying keeps what the app added.
    [Fact]
    public void SharedFileTheAppRewrites()
    {
        var p = dir["qt6ct.conf"];
        var rendered = "# Generated by mazapan\n[Appearance]\nstyle=Fusion\n";
        var owned = new Owned();
        var (ch, orphans) = Plan(owned, Shared(p, rendered));
        Assert.Equal(State.New, ch[0].State);
        Apply.Execute(ch, orphans, owned, false);
        Assert.Equal(rendered, ReadText(p)); // a new shared file is written as rendered
        Write(p, "[Appearance]\nstyle=Fusion\n\n[SettingsWindow]\ngeometry=x\n");

        (ch, _) = Plan(owned, Shared(p, rendered));
        Assert.Equal(State.Unchanged, ch[0].State); // the app rewriting its file is not a change
        // A new theme: our key changes, the app's stays.
        (ch, orphans) = Plan(owned, Shared(p, "[Appearance]\nstyle=Windows\n"));
        Assert.Equal(State.Changed, ch[0].State);
        Apply.Execute(ch, orphans, owned, false);
        var b = ReadText(p);
        Assert.Contains("style=Windows", b);
        Assert.Contains("geometry=x", b);
    }

    [Fact]
    public void SharedFileEditedKeyIsAConflict()
    {
        var p = dir["kdeglobals"];
        var owned = new Owned();
        var (ch, orphans) = Plan(owned, Shared(p, "[KDE]\nwidgetStyle=Fusion\n"));
        Apply.Execute(ch, orphans, owned, false);
        // Someone picked another style in the app: one of mazapan's keys.
        Write(p, "[KDE]\nwidgetStyle=Breeze\n");
        (ch, orphans) = Plan(owned, Shared(p, "[KDE]\nwidgetStyle=Oxygen\n"));
        Assert.Equal(State.Conflict, ch[0].State);
        Assert.Throws<ConflictException>(() => Apply.Execute(ch, orphans, owned, false));
        var res = Apply.Execute(ch, orphans, owned, true);
        Assert.Equal("[KDE]\nwidgetStyle=Breeze\n", ReadText(res.Backups[p]));
        Assert.Contains("widgetStyle=Oxygen", ReadText(p));
        // A shared file's backup is a copy, and private.
        Assert.Equal(UnixFileMode.UserRead | UnixFileMode.UserWrite, System.IO.File.GetUnixFileMode(res.Backups[p]));
    }

    [Fact]
    public void OtherSharedFormats()
    {
        // user.js: someone's arkenfox prefs stay, ours are set or added.
        var js = "user_pref(\"privacy.x\", true);\nuser_pref(\"browser.theme.toolbar-theme\", 2);\n";
        var got = Apply.MergeKeys("prefs", js, Apply.KeysOf("prefs", "user_pref(\"browser.theme.toolbar-theme\", 0);\nuser_pref(\"toolkit.a\", true);\n"));
        Assert.Equal("user_pref(\"privacy.x\", true);\nuser_pref(\"browser.theme.toolbar-theme\", 0);\nuser_pref(\"toolkit.a\", true);\n", got);
        // userChrome.css: their CSS stays, our @import goes first, once.
        var css = "#nav-bar { order: 1 }\n";
        var want = Apply.KeysOf("lines", "@import \"mazapan.css\";\n");
        got = Apply.MergeKeys("lines", css, want);
        Assert.Equal("@import \"mazapan.css\";\n#nav-bar { order: 1 }\n", got);
        Assert.Equal(got, Apply.MergeKeys("lines", got, want));
        // Chromium's Preferences: its keys stay, our leaf is set.
        got = Apply.MergeKeys("json", "{\"extensions\":{\"theme\":{\"id\":\"x\"},\"other\":1},\"a\":[1,2]}",
            Apply.KeysOf("json", "{\"extensions\":{\"theme\":{\"system_theme\":1}}}"));
        var keys = Apply.KeysOf("json", got);
        Assert.Equal("1", keys["\0extensions\x01theme\x01system_theme"]);
        Assert.Equal("\"x\"", keys["\0extensions\x01theme\x01id"]);
        Assert.Equal("[1,2]", keys["\0a"]);
        // Keys with dots stay keys: VS Code's "workbench.colorTheme".
        got = Apply.MergeKeys("json", "{\"workbench.colorTheme\":\"A\"}", Apply.KeysOf("json", "{\"workbench.colorTheme\":\"B\"}"));
        Assert.Equal("{\"workbench.colorTheme\":\"B\"}", got);
    }

    // A settings.json people read stays indented; one line stays one line (a
    // browser's Preferences); mazapan's keys leave, and the objects they empty.
    [Fact]
    public void JsonLayoutAndDrop()
    {
        var want = Apply.KeysOf("json", "{\"a\":{\"[T]\":{\"x\":\"<1>\"}}}");
        var got = Apply.MergeKeys("json", "{\n\t\"mine\": 1\n}\n", want);
        Assert.Equal("{\n\t\"a\": {\n\t\t\"[T]\": {\n\t\t\t\"x\": \"<1>\"\n\t\t}\n\t},\n\t\"mine\": 1\n}\n", got);
        Assert.DoesNotContain("\n", Apply.MergeKeys("json", "{\"mine\":1}", want));
        Assert.Equal("{\n\t\"mine\": 1\n}\n", Apply.DropKeys("json", got, want));
        // Not JSON (a comment): left exactly as it is.
        Assert.Equal("{ // mine\n}", Apply.MergeKeys("json", "{ // mine\n}", want));
    }

    // What Go's encoder does to a file it rewrites: keys sorted, numbers as
    // float64, empty objects and arrays compact, HTML characters kept in the
    // file but escaped in Owned's keys.
    [Fact]
    public void JsonRewriteIsGos()
    {
        var text = "{\"z\":1.50,\"b\":[],\"a\":{},\"n\":1e21,\"s\":1E-7,\"big\":12345678901234567890,\"t\":\"a<b\\u00e9\\ud83d\\ude00\\b\\u2028\"}";
        var got = Apply.MergeKeys("json", text, Apply.KeysOf("json", "{\"x\":{\"y\":true}}"));
        Assert.Equal("{\"a\":{},\"b\":[],\"big\":12345678901234567000,\"n\":1e+21,\"s\":1e-7,\"t\":\"a<bé😀\\b\\u2028\",\"x\":{\"y\":true},\"z\":1.5}", got);
        var indented = Apply.MergeKeys("json", "", Apply.KeysOf("json", "{\"x\":{\"y\":[1,{\"k\":null}]}}"));
        Assert.Equal("{\n\t\"x\": {\n\t\t\"y\": [\n\t\t\t1,\n\t\t\t{\n\t\t\t\t\"k\": null\n\t\t\t}\n\t\t]\n\t}\n}\n", indented);
        Assert.Equal("\"\\u003c1\\u003e\"", Apply.KeysOf("json", "{\"x\":\"<1>\"}")["\0x"]);
        Assert.Equal("{}", Apply.KeysOf("json", "{\"x\":{}}")["\0x"]);
        // Duplicate keys: the last wins, as in Go.
        Assert.Equal("2", Apply.KeysOf("json", "{\"x\":1,\"x\":2}")["\0x"]);
        // A number beyond float64 doesn't unmarshal in Go: unreadable.
        Assert.False(Apply.Readable("json", "{\"x\":1e400}"));
        Assert.False(Apply.Readable("json", "null"));
        Assert.False(Apply.Readable("json", "[1]"));
        Assert.True(Apply.Readable("json", " {} "));
    }

    [Fact]
    public void GoJsonFloats()
    {
        string F(double f) => GoJsonCodec.FormatFloat(f);
        Assert.Equal("0", F(0));
        Assert.Equal("-0", F(-0.0));
        Assert.Equal("0.000001", F(1e-6));
        Assert.Equal("1e-7", F(1e-7));
        Assert.Equal("1.5e-10", F(1.5e-10));
        Assert.Equal("1e-100", F(1e-100));
        Assert.Equal("100000000000000000000", F(1e20));
        Assert.Equal("1e+21", F(1e21));
        Assert.Equal("1.7976931348623157e+308", F(double.MaxValue));
        Assert.Equal("0.1", F(0.1));
        Assert.Equal("13345678901234568", F(13345678901234567));
    }

    [Fact]
    public void GoJsonSyntaxErrors()
    {
        string E(string s) => Assert.Throws<GoJsonCodec.JsonError>(() => GoJsonCodec.Parse(s)).Message;
        Assert.Equal("unexpected end of JSON input", E(""));
        Assert.Equal("unexpected end of JSON input", E("  "));
        Assert.Equal("invalid character 'x' looking for beginning of value", E("x"));
        Assert.Equal("invalid character '/' looking for beginning of object key string", E("{ // mine\n}"));
        Assert.Equal("invalid character '}' after object key", E("{\"a\"}"));
        Assert.Equal("invalid character ']' after object key:value pair", E("{\"a\":1]"));
        Assert.Equal("invalid character '}' after array element", E("[1}"));
        Assert.Equal("invalid character ']' looking for beginning of value", E("[1,]"));
        Assert.Equal("invalid character 'x' after top-level value", E("{} x"));
        Assert.Equal("invalid character '1' after top-level value", E("01"));
        Assert.Equal("invalid character 'x' in literal true (expecting 'r')", E("tx"));
        Assert.Equal("invalid character '\\n' in string literal", E("\"a\nb\""));
        Assert.Equal("invalid character 'x' in string escape code", E("\"\\x\""));
        Assert.Equal("invalid character '\\'' looking for beginning of value", E("'a'"));
        Assert.Equal("invalid character '.' after decimal point in numeric literal", E("1.."));
        Assert.Equal("invalid character 'x' in \\u hexadecimal character escape", E("\"\\u00x0\""));
    }

    [Fact]
    public void SharedFormatsEdgeCases()
    {
        // An @import after other rules is ignored by CSS: not there.
        Assert.Empty(Apply.KeysOf("lines", "#a { color: red }\n@import \"mazapan.css\";\n"));
        Assert.Equal("1", Apply.KeysOf("lines", "/* mine\n   more */\n@charset \"utf-8\";\n@import \"mazapan.css\";\n#a{}\n")["\0@import \"mazapan.css\";"]);
        // A commented-out pref isn't set; single quotes and a trailing comment.
        var k = Apply.KeysOf("prefs", "/*\nuser_pref(\"a\", true);\n*/\nuser_pref('b', 1); // mine\n");
        Assert.False(k.ContainsKey("\0a"));
        Assert.Equal("1", k["\0b"]);
        Assert.Equal("user_pref(\"b\", 2); // mine\n",
            Apply.MergeKeys("prefs", "user_pref('b', 1); // mine\n", new Dictionary<string, string> { ["\0b"] = "2" }));
    }

    // In a person's own user.js: a pref a newer plugin version drops goes (as
    // mazapan wrote it), theirs stay; when the plugin goes, its lines go too.
    [Fact]
    public void PersonsFileLetsGo()
    {
        var p = dir["user.js"];
        Write(p, "user_pref(\"mine\", 1);\n");
        var v1 = new RenderedFile { Plugin = "p", Path = p, Merge = "prefs", Content = "user_pref(\"a\", true);\nuser_pref(\"old\", 0);\n" };
        var owned = new Owned();
        var (ch, orphans) = Plan(owned, v1);
        Apply.Execute(ch, orphans, owned, false);

        var v2 = new RenderedFile { Plugin = "p", Path = p, Merge = "prefs", Content = "user_pref(\"a\", true);\n" };
        (ch, orphans) = Plan(owned, v2);
        Assert.Equal(State.Changed, ch[0].State); // a dropped pref is a change
        Apply.Execute(ch, orphans, owned, false);
        Assert.Equal("user_pref(\"mine\", 1);\nuser_pref(\"a\", true);\n", ReadText(p));
        (ch, orphans) = Plan(owned);
        Apply.Execute(ch, orphans, owned, false);
        Assert.Equal("user_pref(\"mine\", 1);\n", ReadText(p)); // after the plugin went
    }

    // Taking mazapan's @import out of your userChrome.css (to opt a profile
    // out) is an edit: not put back silently.
    [Fact]
    public void RemovedLineIsAnEdit()
    {
        var p = dir["userChrome.css"];
        var f = new RenderedFile { Plugin = "p", Path = p, Content = "@import \"mazapan.css\";\n", Merge = "lines" };
        var owned = new Owned();
        var (ch, orphans) = Plan(owned, f);
        Apply.Execute(ch, orphans, owned, false);
        Write(p, "#mine {}\n");
        Assert.Equal(State.Conflict, Plan(owned, f).Changes[0].State);
    }

    // A JSON file that doesn't parse is never rewritten blind; a busy one
    // (its app running) isn't touched at all.
    [Fact]
    public void UnreadableAndBusy()
    {
        var p = dir["Preferences"];
        Write(p, "{\"a\":1,}");
        System.IO.File.SetUnixFileMode(p, UnixFileMode.UserRead | UnixFileMode.UserWrite);
        var f = new RenderedFile { Plugin = "p", Path = p, Content = "{\"x\":1}", Merge = "json" };
        var (ch, orphans) = Plan(new Owned(), f);
        Assert.Equal(State.Unreadable, ch[0].State);
        Apply.Execute(ch, orphans, new Owned(), true);
        Assert.Equal("{\"a\":1,}", ReadText(p)); // untouched, even with --adopt
        Write(p, "{\"a\":1}");
        f.Busy = true;
        var owned = new Owned { [p] = "json:old" };
        (ch, orphans) = Plan(owned, f);
        Assert.Equal(State.Busy, ch[0].State);
        Apply.Execute(ch, orphans, owned, false);
        Assert.Equal("{\"a\":1}", ReadText(p));
        Assert.Equal("json:old", owned[p]);
        // Rewritten, a 0600 file stays 0600.
        f.Busy = false;
        (ch, orphans) = Plan(new Owned(), f);
        Apply.Execute(ch, orphans, new Owned(), false);
        Assert.Equal("{\"a\":1,\"x\":1}", ReadText(p));
        Assert.Equal(UnixFileMode.UserRead | UnixFileMode.UserWrite, System.IO.File.GetUnixFileMode(p));
    }

    // A person's own kdeglobals, never written by mazapan: its own value for one
    // of mazapan's keys is theirs (a conflict); keys it lacks are just added.
    [Fact]
    public void SharedFileFirstTime()
    {
        var mine = dir["kdeglobals"];
        Write(mine, "[KDE]\nwidgetStyle=Breeze\n[KFileDialog Settings]\nx=1\n");
        Assert.Equal(State.Conflict, Plan(new Owned(), Shared(mine, "[KDE]\nwidgetStyle=Fusion\n")).Changes[0].State);
        var sparse = dir["qt6ct.conf"];
        Write(sparse, "[SettingsWindow]\ngeometry=x\n");
        Assert.Equal(State.Changed, Plan(new Owned(), Shared(sparse, "[Appearance]\nstyle=Fusion\n")).Changes[0].State);
    }

    // A shared file kept in a dotfiles repo, linked from ~/.config: written
    // through the link, which stays a link.
    [Fact]
    public void SharedFileThroughSymlink()
    {
        string real = dir["dotfiles-kdeglobals"], link = dir["kdeglobals"];
        Write(real, "[General]\nx=1\n");
        System.IO.File.CreateSymbolicLink(link, real);
        var owned = new Owned();
        var (ch, orphans) = Plan(owned, Shared(link, "[KDE]\nwidgetStyle=Fusion\n"));
        Apply.Execute(ch, orphans, owned, false);
        Assert.NotNull(new FileInfo(link).LinkTarget); // the link was not replaced by a file
        var b = ReadText(real);
        Assert.Contains("widgetStyle=Fusion", b);
        Assert.Contains("x=1", b);
    }

    // A file owned whole by an older version, then rewritten by the app, is
    // merged into, not a conflict; and a shared orphan stays.
    [Fact]
    public void SharedFileFromWholeAndOrphan()
    {
        var p = dir["qt6ct.conf"];
        Write(p, "[Appearance]\nstyle=Fusion\n[SettingsWindow]\ngeometry=x\n");
        var owned = new Owned { [p] = Apply.Sum("# old\n[Appearance]\nstyle=Fusion\n") };
        var (ch, orphans) = Plan(owned, Shared(p, "[Appearance]\nstyle=Fusion\nicon_theme=A\n"));
        Assert.Equal(State.Changed, ch[0].State);
        Apply.Execute(ch, orphans, owned, false);
        (ch, orphans) = Plan(owned);
        var res = Apply.Execute(ch, orphans, owned, false);
        Assert.True(System.IO.File.Exists(p)); // a shared file stays when its plugin goes
        Assert.Single(res.Shared);
    }

    [Fact]
    public void SharedOwnedRoundTrips()
    {
        var keys = Apply.IniKeys("[b]\nk=2\n[a]\nk=1\n");
        var s = Apply.SharedOwned("ini", keys);
        Assert.Equal("ini:a\0k\01\nb\0k\02", s);
        Assert.True(Apply.FromSharedOwned(s, out var back, out var format));
        Assert.Equal("ini", format);
        Assert.Equal(keys.OrderBy(kv => kv.Key), back.OrderBy(kv => kv.Key));
        Assert.False(Apply.IsShared(Apply.Sum("x")));
    }
}
