<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>myarch</AssemblyName>
    <RootNamespace>MyArch</RootNamespace>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="MyArch.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Scriban" Version="7.5.0" />
    <PackageReference Include="Tomlyn" Version="2.10.1" />
  </ItemGroup>
</Project>
